using System.Collections.Immutable;
using System.Reflection.Metadata;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;
using static NCoreUtils.Json.SyntaxFactoryHelper;

namespace NCoreUtils.Json;

internal static class EnumConverterEmitter
{
    private static SyntaxTriviaList SyntaxTriviaList { get; } = TriviaList(
        Comment("// <auto-generated/>"),
        Trivia(NullableDirectiveTrivia(Token(SyntaxKind.EnableKeyword), true))
    );

    private static NameSyntax JsonTokenTypeString { get; } = ParseName("System.Text.Json.JsonTokenType.String");


    private static MethodDeclarationSyntax EmitStaticReadMethod(EnumConverterTarget target, ImmutableArray<EnumField> fields)
    {
        var stmts = new List<StatementSyntax>(fields.Length + 2)
        {
            IfStatement(
                condition: NotEqualsExpression(
                    SimpleMemberAccessExpression(IdentifierNames.reader, IdentifierNames.TokenType),
                    JsonTokenTypeString
                ),
                statement: BracedBlock(ThrowStatement(
                    NewExpression(
                        Types.JsonException,
                        InterpolatedStringExpression(
                            Tokens.InterpolatedStringStart,
                            List(new InterpolatedStringContentSyntax[]
                            {
                                InterpolatedStringText($"Unable to read {target.EnumFullName} from JSON sequence starting with "),
                                Interpolation(SimpleMemberAccessExpression(IdentifierNames.reader, IdentifierNames.TokenType)),
                                InterpolatedStringText(".")
                            }),
                            Tokens.InterpolatedStringEnd
                        )
                    )
                ))
            )
        };
        foreach (var field in fields)
        {
            stmts.Add(EmitArm(target.EnumType, field));
        }
        stmts.Add(
            ThrowStatement(
                NewExpression(
                    Types.JsonException,
                    InterpolatedStringExpression(
                        Tokens.InterpolatedStringStart,
                        List(new InterpolatedStringContentSyntax[]
                        {
                            InterpolatedStringText("\\\""),
                            Interpolation(SimpleInvocationExpression(SimpleMemberAccessExpression(IdentifierNames.reader, IdentifierNames.GetString))),
                            InterpolatedStringText($"\\\" is not a valid value for {target.EnumFullName}."),
                        }),
                        Tokens.InterpolatedStringEnd
                    )
                )
            )
        );

        return MethodDeclaration(
            attributeLists: default,
            modifiers: TokenList(Keywords.Public, Keywords.Static),
            returnType: target.EnumType,
            explicitInterfaceSpecifier: default!,
            identifier: Identifiers.Read,
            typeParameterList: default!,
            parameterList: ParameterList(SingletonSeparatedList(
                Parameter(default, TokenList(Keywords.Ref), Types.Utf8JsonReader, Identifiers.reader, default)
            )),
            constraintClauses: default,
            body: Block(stmts),
            semicolonToken: default
        );


        static IfStatementSyntax EmitArm(TypeSyntax enumType, EnumField field)
            => IfStatement(
                SimpleInvocationExpression(
                    SimpleMemberAccessExpression(
                        IdentifierNames.reader,
                        IdentifierNames.ValueTextEquals
                    ),
                    Utf8StringLiteralExpression(field.JsonValue)
                ),
                BracedBlock(
                    ReturnStatement(SimpleMemberAccessExpression(enumType, field.IdentifierName))
                )
            );
    }

    private static MethodDeclarationSyntax EmitStaticWriteMethod(EnumConverterTarget target, ImmutableArray<EnumField> fields)
    {
        StatementSyntax fallback = BracedBlock(ThrowStatement(
            NewExpression(
                Types.JsonException,
                InterpolatedStringExpression(
                    Tokens.InterpolatedStringStart,
                    List(new InterpolatedStringContentSyntax[]
                    {
                        InterpolatedStringText("\\\""),
                        Interpolation(IdentifierNames.value),
                        InterpolatedStringText($"\\\" is not a valid value for {target.EnumFullName}."),
                    }),
                    Tokens.InterpolatedStringEnd
                )
            )
        ));

        var body = fields.Aggregate(fallback, (@else, field) =>
        {
            return IfStatement(
                condition: EqualsExpression(
                    SimpleMemberAccessExpression(target.EnumType, field.IdentifierName),
                    IdentifierNames.value
                ),
                statement: BracedBlock(ExpressionStatement(SimpleInvocationExpression(
                    SimpleMemberAccessExpression(
                        IdentifierNames.writer,
                        IdentifierNames.WriteStringValue
                    ),
                    Utf8StringLiteralExpression(field.JsonValue)
                ))),
                @else: ElseClause(@else)
            );
        });

        return MethodDeclaration(
            attributeLists: default,
            modifiers: TokenList(Keywords.Public, Keywords.Static),
            returnType: Types.Void,
            explicitInterfaceSpecifier: default!,
            identifier: Identifiers.Write,
            typeParameterList: default!,
            parameterList: ParameterList(SeparatedList([
                Parameter(default, default, Types.Utf8JsonWriter, Identifiers.writer, default),
                Parameter(default, default, target.EnumType, Identifiers.value, default)
            ])),
            constraintClauses: default,
            body: BracedBlock(body),
            semicolonToken: default
        );
    }

    private static ParameterListSyntax ReadParameters { get; } = ParameterList(SeparatedList([
        Parameter(default, TokenList(Keywords.Ref), Types.Utf8JsonReader, Identifiers.reader, default),
        Parameter(default, default, Types.Type, Identifier("typeToConvert"), default),
        Parameter(default, default, Types.JsonSerializerOptions, Identifiers.options, default)
    ]));

    private static MethodDeclarationSyntax EmitOverrideReadMethod(EnumConverterTarget target)
    {
        return MethodDeclaration(
            attributeLists: default,
            modifiers: TokenList(Keywords.Public, Keywords.Override),
            returnType: target.EnumType,
            explicitInterfaceSpecifier: default!,
            identifier: Identifiers.Read,
            typeParameterList: default!,
            parameterList: ReadParameters,
            constraintClauses: default,
            body: default,
            expressionBody: ArrowExpressionClause(InvocationExpression(
                IdentifierNames.Read,
                ArgumentList(
                    openParenToken: Tokens.OpenParen,
                    SingletonSeparatedList(Argument(default, Keywords.Ref, IdentifierNames.reader)),
                    closeParenToken: Tokens.CloseParen
                )
            )),
            semicolonToken: Tokens.Semicolon
        );
    }

    private static MethodDeclarationSyntax EmitOverrideWriteMethod(EnumConverterTarget target)
    {
        return MethodDeclaration(
            attributeLists: default,
            modifiers: TokenList(Keywords.Public, Keywords.Override),
            returnType: Types.Void,
            explicitInterfaceSpecifier: default!,
            identifier: Identifiers.Write,
            typeParameterList: default!,
            parameterList: ParameterList(SeparatedList([
                Parameter(default, default, Types.Utf8JsonWriter, Identifiers.writer, default),
                Parameter(default, default, target.EnumType, Identifiers.value, default),
                Parameter(default, default, Types.JsonSerializerOptions, Identifiers.options, default)
            ])),
            constraintClauses: default,
            body: default,
            expressionBody: ArrowExpressionClause(SimpleInvocationExpression(
                IdentifierNames.Write,
                IdentifierNames.writer,
                IdentifierNames.value
            )),
            semicolonToken: Tokens.Semicolon
        );
    }

    private static ClassDeclarationSyntax EmitClass(EnumConverterTarget target)
    {
        return ClassDeclaration(
            attributeLists: default,
            modifiers: TokenList(Keywords.Partial),
            identifier: Identifier(target.ConverterName),
            typeParameterList: default,
            baseList: default,
            constraintClauses: default,
            members: List(new MemberDeclarationSyntax[]
            {
                EmitStaticReadMethod(target, target.Fields),
                EmitStaticWriteMethod(target, target.Fields),
                EmitOverrideReadMethod(target),
                EmitOverrideWriteMethod(target)
            })
        );
    }

    public static CompilationUnitSyntax EmitUnit(EnumConverterTarget target)
    {
        CompilationUnitSyntax unitSyntax = CompilationUnit()
            .AddMembers(
                NamespaceDeclaration(IdentifierName(target.Namespace))
                    .WithLeadingTrivia(SyntaxTriviaList)
                    .AddMembers(EmitClass(target))
            )
            .NormalizeWhitespace();
        return unitSyntax;
    }
}